"""Multi-target command emission.

A command is authored once as an Agent Skills ``SKILL.md`` under a brain's
``03-templates/agent-commands/{core,extensions}/<base>/``. This module emits that
single source into the standard discovery locations each agent runtime reads, so
the same command works across vendors (see ADR 0020 and ADR 0022):

- ``.claude/skills/<name>/SKILL.md``   — Claude Code
- ``.github/skills/<name>/SKILL.md``   — GitHub Copilot (Agent Skills spec)
- ``.github/agents/<name>.agent.md``   — GitHub Copilot (custom agents)

Every emitted file is generated from the canonical ``SKILL.md`` and carries a
marker comment; re-running refreshes them and prunes generated files for commands
that no longer exist, without touching hand-authored agents/skills. Standard
library only.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator

GENERATED_NOTE = (
    "<!-- generated by `brainfactory emit-commands` from "
    "03-templates/agent-commands; do not edit by hand -->"
)


@dataclass
class EmitResult:
    brain: str
    commands: list[str] = field(default_factory=list)
    written: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    ok: bool = True
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "brain": self.brain,
            "ok": self.ok,
            "commands": self.commands,
            "written": self.written,
            "removed": self.removed,
            "notes": self.notes,
        }


def _split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return ``(meta, body)`` from a SKILL.md with ``---`` YAML frontmatter."""
    if not text.startswith("---"):
        return {}, text
    lines = text.splitlines()
    close = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if close is None:
        return {}, text
    meta: dict[str, str] = {}
    for line in lines[1:close]:
        if ":" in line:
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip()
    body = "\n".join(lines[close + 1:]).lstrip("\n")
    return meta, body


def _command_sources(brain: Path) -> Iterator[tuple[str, str, Path]]:
    """Yield ``(scope, base_name, skill_path)`` for every authored command."""
    base = brain / "03-templates" / "agent-commands"
    for scope in ("core", "extensions"):
        scope_dir = base / scope
        if not scope_dir.is_dir():
            continue
        for sub in sorted(scope_dir.iterdir()):
            skill = sub / "SKILL.md"
            if sub.is_dir() and skill.is_file():
                yield scope, sub.name, skill


def _clean_generated(root: Path, result: EmitResult, brain: Path) -> None:
    """Remove previously generated files (marker-tagged) and prune empty dirs."""
    if not root.is_dir():
        return
    for path in sorted(root.rglob("*")):
        if path.is_file():
            try:
                if GENERATED_NOTE in path.read_text(encoding="utf-8"):
                    path.unlink()
                    result.removed.append(str(path.relative_to(brain)))
            except (OSError, UnicodeDecodeError):
                continue
    for path in sorted(root.rglob("*"), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def _write(path: Path, content: str, result: EmitResult, brain: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not content.endswith("\n"):
        content += "\n"
    path.write_text(content, encoding="utf-8")
    result.written.append(str(path.relative_to(brain)))


def _skill_copy(text: str) -> str:
    """Faithful SKILL.md copy with a trailing generated marker."""
    return f"{text.rstrip()}\n\n{GENERATED_NOTE}\n"


def _agent_md(name: str, description: str, body: str) -> str:
    """A GitHub Copilot custom agent (.agent.md) built from the skill."""
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        "---\n\n"
        f"{GENERATED_NOTE}\n\n"
        f"{body.rstrip()}\n"
    )


def emit_targets(brain: str | Path) -> EmitResult:
    """Emit every authored command to the standard agent discovery locations."""
    brain = Path(brain)
    result = EmitResult(brain=str(brain))

    sources = list(_command_sources(brain))
    if not sources:
        result.ok = False
        result.notes.append(
            "No command sources found under "
            "03-templates/agent-commands/{core,extensions}.")
        return result

    claude_skills = brain / ".claude" / "skills"
    gh_skills = brain / ".github" / "skills"
    gh_agents = brain / ".github" / "agents"

    for root in (claude_skills, gh_skills, gh_agents):
        _clean_generated(root, result, brain)

    for _scope, base_name, skill_path in sources:
        text = skill_path.read_text(encoding="utf-8")
        meta, body = _split_frontmatter(text)
        name = meta.get("name") or base_name
        description = meta.get("description", "").strip()

        result.commands.append(name)
        _write(claude_skills / name / "SKILL.md", _skill_copy(text), result, brain)
        _write(gh_skills / name / "SKILL.md", _skill_copy(text), result, brain)
        _write(gh_agents / f"{name}.agent.md",
               _agent_md(name, description, body), result, brain)

    result.notes.append(
        f"Emitted {len(result.commands)} command(s) to "
        ".claude/skills, .github/skills, and .github/agents.")
    return result


def render_report(result: EmitResult) -> str:
    lines = [f"=== emit-commands: {result.brain} ==="]
    lines.append(
        f"commands: {len(result.commands)}  written: {len(result.written)}  "
        f"removed (stale): {len(result.removed)}")
    for command in result.commands:
        lines.append(f"  + {command}")
    for note in result.notes:
        lines.append(note)
    return "\n".join(lines)
